// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_devices.sql

package sql

import (
	"context"
	"database/sql"
)

const upsertContactDevice = `-- name: UpsertContactDevice :exec
INSERT INTO contact_devices (
	contact_user_id,
	device_id,
	public_key,
	created_at,
	revoked_at
) VALUES (
	?, ?, ?, ?, ?
)
ON CONFLICT(contact_user_id, device_id) DO UPDATE SET
	public_key = excluded.public_key,
	created_at = excluded.created_at,
	revoked_at = excluded.revoked_at
`

type UpsertContactDeviceParams struct {
	ContactUserID string        `db:"contact_user_id" json:"contact_user_id"`
	DeviceID      string        `db:"device_id" json:"device_id"`
	PublicKey     []byte        `db:"public_key" json:"public_key"`
	CreatedAt     int64         `db:"created_at" json:"created_at"`
	RevokedAt     sql.NullInt64 `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) UpsertContactDevice(ctx context.Context, arg UpsertContactDeviceParams) error {
	_, err := q.db.ExecContext(ctx, upsertContactDevice,
		arg.ContactUserID,
		arg.DeviceID,
		arg.PublicKey,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}
