// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_requests.sql

package sql

import (
	"context"
)

const deleteContactRequestByFromUserID = `-- name: DeleteContactRequestByFromUserID :exec
DELETE FROM contact_requests
WHERE from_user_id = ?
`

func (q *Queries) DeleteContactRequestByFromUserID(ctx context.Context, fromUserID string) error {
	_, err := q.db.ExecContext(ctx, deleteContactRequestByFromUserID, fromUserID)
	return err
}

const listContactRequests = `-- name: ListContactRequests :many
SELECT id, from_user_id, name, username, from_contact_code, created_at
FROM contact_requests
ORDER BY created_at ASC
`

func (q *Queries) ListContactRequests(ctx context.Context) ([]ContactRequest, error) {
	rows, err := q.db.QueryContext(ctx, listContactRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactRequest{}
	for rows.Next() {
		var i ContactRequest
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.Name,
			&i.Username,
			&i.FromContactCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContactRequest = `-- name: UpsertContactRequest :exec
INSERT INTO contact_requests (
  from_user_id,
  name,
  username,
  from_contact_code,
  created_at
) VALUES (
  ?, ?, ?, ?, ?
)
ON CONFLICT(from_user_id) DO UPDATE SET
  name = excluded.name,
  username = excluded.username,
  from_contact_code = excluded.from_contact_code,
  created_at = excluded.created_at
`

type UpsertContactRequestParams struct {
	FromUserID      string `db:"from_user_id" json:"from_user_id"`
	Name            string `db:"name" json:"name"`
	Username        string `db:"username" json:"username"`
	FromContactCode string `db:"from_contact_code" json:"from_contact_code"`
	CreatedAt       int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertContactRequest(ctx context.Context, arg UpsertContactRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertContactRequest,
		arg.FromUserID,
		arg.Name,
		arg.Username,
		arg.FromContactCode,
		arg.CreatedAt,
	)
	return err
}
