// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sql

import (
	"context"
)

const listContacts = `-- name: ListContacts :many
SELECT id, user_id, name, username, profile_picture_url, contact_code, created_at
FROM contacts
ORDER BY created_at ASC
`

func (q *Queries) ListContacts(ctx context.Context) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.ProfilePictureUrl,
			&i.ContactCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (
  user_id,
  name,
  username,
  contact_code,
	profile_picture_url,
  created_at
) VALUES (
  ?, ?, ?, ?, ?, ?
)
ON CONFLICT(user_id) DO UPDATE SET
  name = excluded.name,
  username = excluded.username,
  contact_code = excluded.contact_code,
  profile_picture_url = excluded.profile_picture_url,
  created_at = excluded.created_at
`

type UpsertContactParams struct {
	UserID            string `db:"user_id" json:"user_id"`
	Name              string `db:"name" json:"name"`
	Username          string `db:"username" json:"username"`
	ContactCode       string `db:"contact_code" json:"contact_code"`
	ProfilePictureUrl string `db:"profile_picture_url" json:"profile_picture_url"`
	CreatedAt         int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.UserID,
		arg.Name,
		arg.Username,
		arg.ContactCode,
		arg.ProfilePictureUrl,
		arg.CreatedAt,
	)
	return err
}
