// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sql

import (
	"context"
)

const getLocalIdentityByUserID = `-- name: GetLocalIdentityByUserID :one
SELECT id, user_id, device_id, device_public_key, encrypted_device_private_key, kdf_salt, kdf_params, name, local_handle, profile_picture_path, contact_code, created_at
FROM local_identity
WHERE user_id = ?
`

func (q *Queries) GetLocalIdentityByUserID(ctx context.Context, userID string) (LocalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getLocalIdentityByUserID, userID)
	var i LocalIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.DevicePublicKey,
		&i.EncryptedDevicePrivateKey,
		&i.KdfSalt,
		&i.KdfParams,
		&i.Name,
		&i.LocalHandle,
		&i.ProfilePicturePath,
		&i.ContactCode,
		&i.CreatedAt,
	)
	return i, err
}
