// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sql

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
	id,
	name,
	username,
	hashed_password
) VALUES (
	?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID             string `db:"id" json:"id"`
	Name           string `db:"name" json:"name"`
	Username       string `db:"username" json:"username"`
	HashedPassword string `db:"hashed_password" json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.HashedPassword,
	)
	return err
}

const deleteCurrentSession = `-- name: DeleteCurrentSession :exec
DELETE FROM sessions
WHERE id = 1
`

func (q *Queries) DeleteCurrentSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteCurrentSession)
	return err
}

const getCurrentSession = `-- name: GetCurrentSession :one
SELECT
	id,
	session_id,
	user_id,
	created_at,
	expires_at
FROM sessions
WHERE id = 1
`

func (q *Queries) GetCurrentSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getCurrentSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id,
  name,
  username,
  hashed_password
FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.HashedPassword,
	)
	return i, err
}

const upsertCurrentSession = `-- name: UpsertCurrentSession :exec
INSERT INTO sessions (
	id,
	session_id,
	user_id,
	created_at,
	expires_at
) VALUES (
	1, ?, ?, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
	session_id = excluded.session_id,
	user_id = excluded.user_id,
	created_at = excluded.created_at,
	expires_at = excluded.expires_at
`

type UpsertCurrentSessionParams struct {
	SessionID string `db:"session_id" json:"session_id"`
	UserID    string `db:"user_id" json:"user_id"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	ExpiresAt int64  `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpsertCurrentSession(ctx context.Context, arg UpsertCurrentSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrentSession,
		arg.SessionID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}
