// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sql

import (
	"context"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participants (conversation_id, participant_id)
VALUES (?, ?)
`

type AddParticipantParams struct {
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	ParticipantID  string `db:"participant_id" json:"participant_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant, arg.ConversationID, arg.ParticipantID)
	return err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, name)
VALUES (?, ?)
`

type CreateConversationParams struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation, arg.ID, arg.Name)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, name
FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversationByID(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getConversationsByUserID = `-- name: GetConversationsByUserID :many
SELECT conversations.id, conversations.name
FROM conversations
JOIN conversation_participants ON conversation_participants.conversation_id = conversations.id
WHERE conversation_participants.participant_id = ?
ORDER BY conversations.id DESC
`

func (q *Queries) GetConversationsByUserID(ctx context.Context, participantID string) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, getConversationsByUserID, participantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
