// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package sql

import (
	"context"
)

const listFriends = `-- name: ListFriends :many
SELECT
  id,
  user_id,
  name,
  username,
  friend_code,
  created_at
FROM friends
ORDER BY created_at ASC
`

func (q *Queries) ListFriends(ctx context.Context) ([]Friend, error) {
	rows, err := q.db.QueryContext(ctx, listFriends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friend{}
	for rows.Next() {
		var i Friend
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.FriendCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFriend = `-- name: UpsertFriend :exec
INSERT INTO friends (
  user_id,
  name,
  username,
  friend_code,
  created_at
) VALUES (
  ?, ?, ?, ?, ?
)
ON CONFLICT(user_id) DO UPDATE SET
  name = excluded.name,
  username = excluded.username,
  friend_code = excluded.friend_code,
  created_at = excluded.created_at
`

type UpsertFriendParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	Name       string `db:"name" json:"name"`
	Username   string `db:"username" json:"username"`
	FriendCode string `db:"friend_code" json:"friend_code"`
	CreatedAt  int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertFriend(ctx context.Context, arg UpsertFriendParams) error {
	_, err := q.db.ExecContext(ctx, upsertFriend, arg.UserID, arg.Name, arg.Username, arg.FriendCode, arg.CreatedAt)
	return err
}
