// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friend_requests.sql

package sql

import (
	"context"
)

const deleteFriendRequestByFromUserID = `-- name: DeleteFriendRequestByFromUserID :exec
DELETE FROM friend_requests
WHERE from_user_id = ?
`

func (q *Queries) DeleteFriendRequestByFromUserID(ctx context.Context, fromUserID string) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequestByFromUserID, fromUserID)
	return err
}

const listFriendRequests = `-- name: ListFriendRequests :many
SELECT id, from_user_id, name, username, from_friend_code, created_at
FROM friend_requests
ORDER BY created_at ASC
`

func (q *Queries) ListFriendRequests(ctx context.Context) ([]FriendRequest, error) {
	rows, err := q.db.QueryContext(ctx, listFriendRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FriendRequest{}
	for rows.Next() {
		var i FriendRequest
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.Name,
			&i.Username,
			&i.FromFriendCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFriendRequest = `-- name: UpsertFriendRequest :exec
INSERT INTO friend_requests (
  from_user_id,
  name,
  username,
  from_friend_code,
  created_at
) VALUES (
  ?, ?, ?, ?, ?
)
ON CONFLICT(from_user_id) DO UPDATE SET
  name = excluded.name,
  username = excluded.username,
  from_friend_code = excluded.from_friend_code,
  created_at = excluded.created_at
`

type UpsertFriendRequestParams struct {
	FromUserID     string `db:"from_user_id" json:"from_user_id"`
	Name           string `db:"name" json:"name"`
	Username       string `db:"username" json:"username"`
	FromFriendCode string `db:"from_friend_code" json:"from_friend_code"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertFriendRequest(ctx context.Context, arg UpsertFriendRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertFriendRequest,
		arg.FromUserID,
		arg.Name,
		arg.Username,
		arg.FromFriendCode,
		arg.CreatedAt,
	)
	return err
}
