// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sql

type Conversation struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type ConversationParticipant struct {
	ID             int64  `db:"id" json:"id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	ParticipantID  string `db:"participant_id" json:"participant_id"`
}

type Message struct {
	ID             int64  `db:"id" json:"id"`
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	SenderID       string `db:"sender_id" json:"sender_id"`
	Body           string `db:"body" json:"body"`
	CreatedAt      int64  `db:"created_at" json:"created_at"`
}

type Session struct {
	ID        int64  `db:"id" json:"id"`
	SessionID string `db:"session_id" json:"session_id"`
	UserID    string `db:"user_id" json:"user_id"`
	CreatedAt int64  `db:"created_at" json:"created_at"`
	ExpiresAt int64  `db:"expires_at" json:"expires_at"`
}

type User struct {
	ID             string `db:"id" json:"id"`
	Name           string `db:"name" json:"name"`
	Username       string `db:"username" json:"username"`
	HashedPassword string `db:"hashed_password" json:"hashed_password"`
}
