// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sql

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, username, hashed_password, profile_picture_url, friend_code
FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.HashedPassword,
		&i.ProfilePictureUrl,
		&i.FriendCode,
	)
	return i, err
}
