/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/albe194e/albz/app/core-go/ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "auth.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "conversations.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "files.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "messages.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "qr.go"

#include <stdint.h>
#include <stdlib.h>

typedef struct {
	unsigned char* data;
	int len;
} ByteBuffer;

#line 1 "cgo-generated-wrapper"

#line 3 "runtime.go"

#include <stdint.h>
#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "social.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int core_try_load_session(uint64_t handle);
extern int core_login(uint64_t handle, char* username, char* password);
extern int core_logout(uint64_t handle);
extern int core_register(uint64_t handle, char* name, char* username, char* password, char* profilePicturePath);
extern int core_open_conversation(uint64_t handle, char* conversationID);
extern char* core_start_direct_conversation(uint64_t handle, char* contactUserID);
extern char* core_create_conversation(uint64_t handle, char* name, char* participantUserIDsJSON);
extern char* core_save_profile_image(uint64_t handle, unsigned char* data, int length, char* filename);
extern int core_send_message(uint64_t handle, char* conversationID, char* body);
extern ByteBuffer core_get_qr_contact(uint64_t handle);
extern void core_bytes_free(unsigned char* data);
extern uint64_t core_create(char* profileName, char* dataDir, char* serverURL);
extern void core_close(uint64_t handle);
extern char* core_config_json(uint64_t handle);
extern char* core_snapshot_json(uint64_t handle);
extern char* core_poll_event_json(uint64_t handle);
extern char* core_take_last_error(void);
extern void core_string_free(char* value);
extern int core_send_contact_request(uint64_t handle, char* contactCode);
extern int core_accept_contact_request(uint64_t handle, char* fromUserID);
extern int core_reject_contact_request(uint64_t handle, char* fromUserID);

#ifdef __cplusplus
}
#endif
